object Dependencies {

    const val kotlin = "org.jetbrains.kotlin:kotlin-stdlib:${Versions.KOTLIN}"

    const val constraintLayout = "androidx.constraintlayout:constraintlayout:2.1.1"
    const val coreKtx = "androidx.core:core-ktx:1.7.0"
    const val appcompat = "androidx.appcompat:appcompat:1.3.1"
    const val activity = "androidx.activity:activity:1.4.0"
    const val fragment = "androidx.fragment:fragment:1.3.6"
    const val activityKtx = "androidx.activity:activity-ktx:1.4.0"
    const val fragmentKtx = "androidx.fragment:fragment-ktx:1.3.6"
    const val material = "com.google.android.material:material:1.3.0"
    const val androidxCore = "androidx.core:core:1.7.0"
    const val androidxAnnotation = "androidx.annotation:annotation:1.3.0"
    const val lifecycleRuntimeKtx = "androidx.lifecycle:lifecycle-runtime-ktx:2.4.0"
    const val lifecycleLiveDataKtx = "androidx.lifecycle:lifecycle-livedata-ktx:2.4.0"
    const val lifecycleLiveDataCoreKtx = "androidx.lifecycle:lifecycle-livedata-core-ktx:2.4.0"
    const val lifecycleViewModelKtx = "androidx.lifecycle:lifecycle-viewmodel-ktx:2.4.0"
    const val junit = "junit:junit:4.13.2"
    const val junitExt = "androidx.test.ext:junit:1.1.2"
    const val espresso = "androidx.test.espresso:espresso-core:3.3.0"
//    const val lifecycleCommon = "androidx.lifecycle:lifecycle-common-java8:2.3.1"
    const val room = "androidx.room:room-compiler:${Versions.ROOM}"
    const val roomKtx = "androidx.room:room-ktx:${Versions.ROOM}"
    const val roomTest = "androidx.room:room-testing:${Versions.ROOM}"
    const val logger = "com.orhanobut:logger:2.2.0"
    const val gSon = "com.google.code.gson:gson:2.8.6"
    const val chart = "com.github.PhilJay:MPAndroidChart:v3.1.0"
    const val broccoli = "me.samlss:broccoli:1.0.0"
    const val coroutinesCore = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.2"
    const val coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.5.2"
    const val okHttp = "com.squareup.okhttp3:okhttp:4.9.0"
    const val logging = "com.squareup.okhttp3:logging-interceptor:4.9.0"
    const val retrofit = "com.squareup.retrofit2:retrofit:2.9.0"
    const val converter = "com.squareup.retrofit2:converter-gson:2.9.0"
    const val cookieJar = "com.github.franmontiel:PersistentCookieJar:v1.0.1"
    // BaseRecyclerViewAdapterHelper +SmartRefreshLayout
    const val adapterHelper = "com.github.CymChad:BaseRecyclerViewAdapterHelper:3.0.4"
    const val refreshCore = "com.scwang.smart:refresh-layout-kernel:2.0.1"
    const val refreshHeader = "com.scwang.smart:refresh-header-material:2.0.1"
    const val refreshFooter = "com.scwang.smart:refresh-footer-ball:2.0.1"
    const val loadSir = "com.kingja.loadsir:loadsir:1.3.8"
    const val pickerView = "com.contrarywind:Android-PickerView:4.1.9"
    const val calendarview = "com.haibin:calendarview:3.7.1"

}